[2023-12-03 22:53:18,432] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T17:38:00.239033+00:00 [queued]>
[2023-12-03 22:53:18,448] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T17:38:00.239033+00:00 [queued]>
[2023-12-03 22:53:18,448] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 22:53:18,448] {taskinstance.py:1357} INFO - Starting attempt 4 of 6
[2023-12-03 22:53:18,448] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 22:53:18,471] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_creation> on 2023-12-03 17:38:00.239033+00:00
[2023-12-03 22:53:18,477] {standard_task_runner.py:52} INFO - Started process 20526 to run task
[2023-12-03 22:53:18,488] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'water_polution', 'data_creation', 'manual__2023-12-03T17:38:00.239033+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/water_polution.py', '--cfg-path', '/tmp/tmpe2fdz0au', '--error-file', '/tmp/tmpac_wk4as']
[2023-12-03 22:53:18,492] {standard_task_runner.py:80} INFO - Job 12: Subtask data_creation
[2023-12-03 22:53:18,557] {task_command.py:369} INFO - Running <TaskInstance: water_polution.data_creation manual__2023-12-03T17:38:00.239033+00:00 [running]> on host MLops.myguest.virtualbox.org
[2023-12-03 22:53:18,624] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=water_polution
AIRFLOW_CTX_TASK_ID=data_creation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T17:38:00.239033+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T17:38:00.239033+00:00
[2023-12-03 22:53:18,628] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 22:53:18,630] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/antosha/project/scripts/data_creation.py']
[2023-12-03 22:53:18,642] {subprocess.py:85} INFO - Output:
[2023-12-03 22:53:22,804] {subprocess.py:92} INFO - Downloading...
[2023-12-03 22:53:22,804] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=19NlsU9_6qfc7q1gdG7Wi22jO7vhlpV07
[2023-12-03 22:53:22,804] {subprocess.py:92} INFO - To: /home/antosha/project/scripts/datasets/dataset.csv
[2023-12-03 22:53:23,057] {subprocess.py:92} INFO -   0%|          | 0.00/368k [00:00<?, ?B/s]100%|██████████| 368k/368k [00:00<00:00, 1.47MB/s]100%|██████████| 368k/368k [00:00<00:00, 1.46MB/s]
[2023-12-03 22:53:23,438] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 22:53:23,465] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=water_polution, task_id=data_creation, execution_date=20231203T173800, start_date=20231203T175318, end_date=20231203T175323
[2023-12-03 22:53:23,520] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 22:53:23,573] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
