[2023-12-03 23:05:30,706] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T18:05:25.013380+00:00 [queued]>
[2023-12-03 23:05:30,714] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T18:05:25.013380+00:00 [queued]>
[2023-12-03 23:05:30,714] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 23:05:30,714] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-03 23:05:30,714] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 23:05:30,730] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_creation> on 2023-12-03 18:05:25.013380+00:00
[2023-12-03 23:05:30,732] {standard_task_runner.py:52} INFO - Started process 22454 to run task
[2023-12-03 23:05:30,744] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'water_polution', 'data_creation', 'manual__2023-12-03T18:05:25.013380+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/water_polution.py', '--cfg-path', '/tmp/tmpqswwyv8r', '--error-file', '/tmp/tmpdapvco26']
[2023-12-03 23:05:30,747] {standard_task_runner.py:80} INFO - Job 17: Subtask data_creation
[2023-12-03 23:05:30,809] {task_command.py:369} INFO - Running <TaskInstance: water_polution.data_creation manual__2023-12-03T18:05:25.013380+00:00 [running]> on host MLops.myguest.virtualbox.org
[2023-12-03 23:05:30,879] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=water_polution
AIRFLOW_CTX_TASK_ID=data_creation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T18:05:25.013380+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T18:05:25.013380+00:00
[2023-12-03 23:05:30,879] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 23:05:30,880] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/antosha/project/scripts/data_creation.py']
[2023-12-03 23:05:30,894] {subprocess.py:85} INFO - Output:
[2023-12-03 23:05:33,894] {subprocess.py:92} INFO - Downloading...
[2023-12-03 23:05:33,894] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=19NlsU9_6qfc7q1gdG7Wi22jO7vhlpV07
[2023-12-03 23:05:33,894] {subprocess.py:92} INFO - To: /home/antosha/project/scripts/datasets/dataset.csv
[2023-12-03 23:05:34,204] {subprocess.py:92} INFO -   0%|          | 0.00/368k [00:00<?, ?B/s]100%|██████████| 368k/368k [00:00<00:00, 1.20MB/s]100%|██████████| 368k/368k [00:00<00:00, 1.19MB/s]
[2023-12-03 23:05:34,347] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 23:05:34,361] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=water_polution, task_id=data_creation, execution_date=20231203T180525, start_date=20231203T180530, end_date=20231203T180534
[2023-12-03 23:05:34,392] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 23:05:34,414] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
