[2023-12-04 00:17:53,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T19:17:50.636636+00:00 [queued]>
[2023-12-04 00:17:53,068] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.data_creation manual__2023-12-03T19:17:50.636636+00:00 [queued]>
[2023-12-04 00:17:53,068] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 00:17:53,068] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-04 00:17:53,068] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 00:17:53,090] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_creation> on 2023-12-03 19:17:50.636636+00:00
[2023-12-04 00:17:53,099] {standard_task_runner.py:52} INFO - Started process 34862 to run task
[2023-12-04 00:17:53,109] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'water_polution', 'data_creation', 'manual__2023-12-03T19:17:50.636636+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/water_polution.py', '--cfg-path', '/tmp/tmp6a7bexlc', '--error-file', '/tmp/tmpc1k_gzjh']
[2023-12-04 00:17:53,109] {standard_task_runner.py:80} INFO - Job 27: Subtask data_creation
[2023-12-04 00:17:53,178] {task_command.py:369} INFO - Running <TaskInstance: water_polution.data_creation manual__2023-12-03T19:17:50.636636+00:00 [running]> on host MLops.myguest.virtualbox.org
[2023-12-04 00:17:53,260] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=water_polution
AIRFLOW_CTX_TASK_ID=data_creation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T19:17:50.636636+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T19:17:50.636636+00:00
[2023-12-04 00:17:53,261] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-04 00:17:53,261] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/antosha/project/scripts/data_creation.py']
[2023-12-04 00:17:53,278] {subprocess.py:85} INFO - Output:
[2023-12-04 00:17:56,154] {subprocess.py:92} INFO - Downloading...
[2023-12-04 00:17:56,154] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=19NlsU9_6qfc7q1gdG7Wi22jO7vhlpV07
[2023-12-04 00:17:56,155] {subprocess.py:92} INFO - To: /home/antosha/project/scripts/datasets/dataset.csv
[2023-12-04 00:17:56,418] {subprocess.py:92} INFO -   0%|          | 0.00/368k [00:00<?, ?B/s]100%|██████████| 368k/368k [00:00<00:00, 1.41MB/s]100%|██████████| 368k/368k [00:00<00:00, 1.40MB/s]
[2023-12-04 00:17:56,864] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-04 00:17:56,895] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=water_polution, task_id=data_creation, execution_date=20231203T191750, start_date=20231203T191753, end_date=20231203T191756
[2023-12-04 00:17:56,921] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-04 00:17:56,968] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
